config/routes.rb
Rails.application.routes.draw do
  root to: "pages#root"
  get "splash", to: "pages#splash"
  get "dashboard", to: "pages#details"
  get "user", to: "users#current"
  
  resources :users
  resource :session, only: [:create, :new, :destroy]
  
  namespace :api, defaults: { format: :json } do
    resources :tasks
    resources :deals, only: [:create, :destroy]
    resources :categories, only: [:show, :index]
    resources :users, only: [] do
      resources :skills, except: [:index]
    end
    resources :skills, only: [:index]
    resources :availabilities, only: [:create, :destroy, :index, :show] do
      resources :availability_markers, only: [:create, :destroy, :index, :show]
    end
  end
  
end

app/views/layouts/_dashboard.html.erb
<div class="row">
  <div class="col-md-7">
    <h2>Greatest Hits</h2>
    <div class="container-fluid">
      <h4>Heists</h4>
      <p>Do you need crew, muscle, or gear? Maybe a driver?</p>
      <button 
        class="btn btn-default pull-right"
        id="heists_button">Find a Lobster</button>
    </div>
  
    <div class="container-fluid">
      <h4>Heists</h4>
      <p>Do you need crew, muscle, or gear? Get a blueprint of the bank and a driver for the getaway car.</p>
      <button 
        class="btn btn-default pull-right"
        id="heists_button">Find a Lobster</button>
    </div>
  
    <div class="container-fluid">
      <h4>Teach a Lesson</h4>
      <p>Is some young punk encroaching on your turf? Nothing like burning down his house to teach him a lesson. Get help collecting protection money.</p>
      <button 
        class="btn btn-default pull-right"
        id="lessons_button">Find a Lobster</button>
    </div>
  
    <div class="container-fluid">
      <h4>Delivery</h4>
      <p>Get help making pickups and dropoffs.</p>
      <button 
        class="btn btn-default pull-right"
        id="delivery_button">Find a Lobster</button>
    </div>
  
    <div class="container-fluid">
      <h4>White Collar</h4>
      <p>A pair of clean hands to handle your dirty work. Lawyers, accountants, hackers, and recon specialists.</p>
      <button 
        class="btn btn-default pull-right"
        id="wc_button">Find a Lobster</button>
    </div>
  </div>

  <div class="col-md-4 col-md-offset-1">
    <h3>Stop Sleeping with the Fishes</h3>
    <div class="col-md-2">
      <a href="#" class="btn btn-default" role="button">
        <strong>Heists</strong><br>
      </a>
    </div>
    <div class="col-md-2">
      <a href="#" class="btn btn-default" role="button">
        <strong>Teach a Lesson</strong><br>
      </a>
    </div>
    <div class="col-md-2">
      <a href="#" class="btn btn-default" role="button">
        <strong>Delivery</strong><br>
      </a>
    </div>
    <div class="col-md-2">
      <a href="#" class="btn btn-default" role="button">
        <strong>White Collar</strong><br>
      </a>
    </div>
  
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="row social">
    <div class="container">
      <span class="social-text">Follow us! We don't pinch:</span>
      <a class="social-link" href="#">
        <%= image_tag("https://s3-us-west-1.amazonaws.com/mobstrlobstr-development/icons/facebook-icon.png", alt: "Facebook", class: "social") %>
      </a>
      | 
      <a class="social-link" href="#">
        <%= image_tag("https://s3-us-west-1.amazonaws.com/mobstrlobstr-development/icons/twitter-bird.png", alt: "Twitter", class: "social") %>
      </a>
      |
      <a class="social-link" href="#">
        <%= image_tag("https://s3-us-west-1.amazonaws.com/mobstrlobstr-development/icons/linkedin-icon.jpg", alt: "Linkedin", class: "social") %>
      </a>
    </div>
  </div>
  <div class="row footer-row">
    <div class="container footer-content col-12">
      <div class="footer-column col-lg-4">
        <span class="footer-title">Discover</span>
        <ul class="links no-bullets">
          <li><a href="http://www.linkedin.com/pub/john-shen/20/a6/b85/">How MobstrLobstr Works</a></li>
          <li><a href="http://www.linkedin.com/pub/john-shen/20/a6/b85/">Become a Lobster</a></li>
          <li><a href="http://www.linkedin.com/pub/john-shen/20/a6/b85/">Trust</a></li>
          <li><a href="http://www.linkedin.com/pub/john-shen/20/a6/b85/">Help</a></li>
        </ul>
      </div>
      <div class="footer-column col-lg-4">
        <span class="footer-title">Company</span>
        <ul class="links no-bullets">
          <li><a href="http://www.linkedin.com/pub/john-shen/20/a6/b85/">About Us</a></li>
          <li><a href="http://www.linkedin.com/pub/john-shen/20/a6/b85/">Careers</a></li>
          <li><a href="http://www.linkedin.com/pub/john-shen/20/a6/b85/">Press</a></li>
          <li><a href="http://www.linkedin.com/pub/john-shen/20/a6/b85/">Blog</a></li>
          <li><a class="inline-links" href="#">Terms &amp; Privacy</a></li>
        </ul>
      </div>
      <div class="footer-column col-lg-4">
        <div class="mobile-apps">
          <div class="footer-title">Download our app</div>
          <p class="apps-message">Maintain your business while shoveling your mountains of cash in the Cayman Islands with our mobile app.</p>
          <a class="appstore-badge" href="#" >
            <%= image_tag("https://s3-us-west-1.amazonaws.com/mobstrlobstr-development/icons/appstore_badge.svg", alt: "Download on the App Store", height: '45') %>  
          </a>
          <a class="appstore-badge" href="#" >
            <%= image_tag("https://s3-us-west-1.amazonaws.com/mobstrlobstr-development/icons/google_play_badge.svg", alt: "Get on Google Play", height: '45') %>
          </a>
          <div class="apps-image"></div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="header">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">
          MobstrLobstr
          <!-- <img src="https://s3-us-west-1.amazonaws.com/mobstrlobstr-development/icons/MobstrLobstr-logo.png"> -->
        </a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
          <li>
            <a href="#">Dashboard</a>
          </li>
          <li>
            <a href="#profile">Profile</a>
          </li>
          <li>
            <%= link_to "Sign out", session_url, method: :delete %>
          </li>
          <% else %>
          <li>
            <a
              data-toggle="modal" 
              data-target="#signup_modal">
              Sign up
            </a>
          </li>
          <li>
            <a
              data-toggle="modal" 
              data-target="#login_modal">
              Log in
            </a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav> 
  <!--End navbar -->

  <!--Start error logs -->
  <% if flash[:errors] %>
  <div class="alert alert-warning alert-dismissible">
     <button 
       type="button" 
       class="close" 
       data-dismiss="alert"><span aria-hidden="true">&times;</span>
     </button>
  <%= flash[:errors].join("<br>") %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobstrLobstr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" 
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>">
  </script>
  <% if signed_in? %>
  <script>
    ML.currentUserID = <%= current_user.id %>;
  </script>
<!--Heap analytics -->
  <script type="text/javascript">
    window.heap=window.heap||[],heap.load=function(t,e){window.heap.appid=t,window.heap.config=e;var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https:":"http:")+"//cdn.heapanalytics.com/js/heap.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(t){return function(){heap.push([t].concat(Array.prototype.slice.call(arguments,0)))}},p=["identify","track"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
    heap.load("1901987013");
  </script>
  <% end %>
</head>
<body>
  <%= render partial: "layouts/header" %>
  <%= yield %>
  <%= render partial: "layouts/footer" %>
</body>
</html>